definitions:
  table.RecordDTO:
    properties:
      id:
        type: string
      table_name:
        type: string
      user_id:
        type: string
      user_score:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/training:
    delete:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      tags:
      - Records
    patch:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      tags:
      - Records
    post:
      consumes:
      - application/json
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: create record struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/table.RecordDTO'
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: ""
      summary: Create record endpoint
      tags:
      - Records
  /api/training/collections:
    delete:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      tags:
      - Collections
    post:
      responses:
        "201":
          description: ""
        "400":
          description: ""
      tags:
      - Collections
  /api/training/collections/get/all:
    get:
      responses:
        "200":
          description: ""
        "400":
          description: ""
      tags:
      - Records
  /api/training/get/{userid}:
    post:
      consumes:
      - application/json
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: userid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
      summary: Get record by user id
      tags:
      - Records
  /api/training/get/all:
    post:
      responses:
        "200":
          description: ""
        "400":
          description: ""
      tags:
      - Records
  /api/training/get/id:
    post:
      consumes:
      - application/json
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: only table_name and id (record_id) required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/table.RecordDTO'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
      summary: Get record by record id
      tags:
      - Records
  /userapi/heartbeat:
    get:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      summary: Heartbeat metric
      tags:
      - Metrics
swagger: "2.0"
